### ISSUE TITLE
翻页功能貌似无法再次服务端渲染，目前有方案否？

### ISSUE THREAD

**Issue by menglingbujie** [warriorBrian/nuxt-blog#1]

**Comment by warriorBrian** [comment]
您好，感谢您的支持！
点击下一页其实是请求了数据，游览器返回200状态。
如果您在`asyncData`中请求，就是在服务器端发起了请求，速度依然要比客户端请求要快了很多。
在nuxt.js更新了2.0中也存在同样的问题，详情请看：[#3999](https://github.com/nuxt/nuxt.js/issues/3999)

**Comment by warriorBrian** [comment]
他的优点就是首屏渲染和SEO优化，当然至今来看有很多不足的地方。因为是服务器端渲染，所以在开发环境缓存很严重、部署占用服务器内存过高等等。这也是需要官方去修正的。
非常感谢您的issues，谢谢！
