### ISSUE TITLE
backpack dev的时候报错了，不支持webpack4吗，webpack版本是4.20

### ISSUE THREAD

**Issue by llxStar** [warriorBrian/nuxt-blog#2]
`backpack dev`

`Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In E:\dir\nuxt-blog\nuxt\node_modules\backpack-core\babel.js
    at createDescriptor (E:\dir\nuxt-blog\nuxt\node_modules\@babel\core\lib\config\config-descriptors.js:178:11)
`

另外题外问个问题，为什么我自己建的demo，asyncData获取数据在组件渲染之后执行，数据没有注入到html里面
`<div id="nuxt-loading" aria-live="polite" role="status">
                <div>Loading...</div>
            </div>`

**Comment by llxStar** [comment]
不用管我另外的问题了，我知道问题了

**Comment by warriorBrian** [comment]
@llxStar  您好，如果您是使用的nuxt2.0是支持webpack4的，而2.0+也是最近更新的。
如果您使用1.4.0+是webpack3版本。

**Comment by llxStar** [comment]
> @llxStar 您好，如果您是使用的nuxt2.0是支持webpack4的，而2.0+也是最近更新的。
> 如果您使用1.4.0+是webpack3版本。

感谢回复，我用的是2.0+的nuxt，可能是一些别的原因，我再找找问题，不占用你的时间啦
