### ISSUE TITLE
请教下关于nuxt部署的一些问题

### ISSUE THREAD

**Issue by ZhengXiaowei** [warriorBrian/nuxt-blog#6]
nuxt和koa都是用在同一个端口3000，部署后，会出现接口找不到或者跨域的问题，请问Nginx上要怎么配置吗？

比如项目路径是`//服务端ip/pro/`
没有做后端的时候页面是可以正常访问的。

做了后端之后，接口地址是`服务端ip/api/` 但是总404.

我感觉应该是我nginx配置的问题：
部分Nginx配置如下：
```
# 项目配置
location /pro/ {
  proxy_pass http://127.0.0.1:3000;
 # 省略其他
}
# 接口的原来是没配的，发现没作用后配的，可实际也没啥作用= =
location /api/ {
 proxy_pass http://127.0.0.1:3000/api/;
}
```

还望指教 谢谢！

**Comment by warriorBrian** [comment]
@ZhengXiaowei 您好，如果是在同一个端口，就说明是写在一起的，前后端没有分离，如果代理应该是不会出现这个问题。
如果放在koa层面去解决这个问题，可以使用koa-cors的依赖包来做允许跨域。但是如果同一个服务下，不会存在跨域的问题。
